name: Build

on:
  workflow_dispatch:

jobs:
  build:
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
    # You might want to Checkout your repo first, but not mandatory
    - name: Check Out
      uses: actions/checkout@v4

    # Cleanup The Actions Workspace Using Custom Composite Run Actions
    
    - name: Prepare the environment
      run: |
        sudo apt update && sudo apt upgrade -y
        DEBIAN_FRONTEND=noninteractive sudo apt install -yq \
            git

    - name: Setup SSH Keys
      uses: webfactory/ssh-agent@v0.9.0
      with:
          ssh-private-key: |
            ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Push
      run: |
        git clone https://github.com/SakuraKyuo/android_kernel_oneplus_sm8650
        cd android_kernel_oneplus_sm8650
        git config http.postBuffer 2147483648
        git config pack.packSizeLimit 500m
        git repack -a -d
        du -sh .git/objects/pack/*.pack | sort -hr
        git remote set-url origin git@github.com:crdroidandroid/android_kernel_oneplus_sm8650
        git branch -M 15.0
        git push -u origin 15.0 -f
